"""empty message

Revision ID: 37e4f4b64b81
Revises: 007cb9b22bf2
Create Date: 2022-03-26 13:13:34.510260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e4f4b64b81'
down_revision = '007cb9b22bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('situacao', sa.String(length=10), nullable=True),
    sa.Column('data_situacao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alergias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('lagradouro', sa.String(length=60), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('setor', sa.String(length=40), nullable=True),
    sa.Column('cidade', sa.String(length=40), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=60), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('doses', sa.Integer(), nullable=False),
    sa.Column('periodicidade', sa.Integer(), nullable=True),
    sa.Column('intervalo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.drop_table('vacinas')
    op.drop_table('usuarios')
    op.drop_table('alergias')
    op.drop_table('agendas')
    # ### end Alembic commands ###
