"""empty message

Revision ID: f7099c61ea0d
Revises: 37e4f4b64b81
Create Date: 2022-03-27 10:47:02.361059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7099c61ea0d'
down_revision = '37e4f4b64b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alergias', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alergias', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alergias', type_='foreignkey')
    op.drop_column('alergias', 'usuario_id')
    # ### end Alembic commands ###
